// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/TrueFlowDev/Backend/internal/module/user/infrastructure/model"
)

func newUsersProfile(db *gorm.DB, opts ...gen.DOOption) usersProfile {
	_usersProfile := usersProfile{}

	_usersProfile.usersProfileDo.UseDB(db, opts...)
	_usersProfile.usersProfileDo.UseModel(&model.UsersProfile{})

	tableName := _usersProfile.usersProfileDo.TableName()
	_usersProfile.ALL = field.NewAsterisk(tableName)
	_usersProfile.ID = field.NewString(tableName, "id")
	_usersProfile.UserID = field.NewString(tableName, "user_id")
	_usersProfile.Email = field.NewString(tableName, "email")
	_usersProfile.FirstName = field.NewString(tableName, "first_name")
	_usersProfile.LastName = field.NewString(tableName, "last_name")
	_usersProfile.Headline = field.NewString(tableName, "headline")
	_usersProfile.Bio = field.NewString(tableName, "bio")
	_usersProfile.CreatedAt = field.NewTime(tableName, "created_at")
	_usersProfile.UpdatedAt = field.NewTime(tableName, "updated_at")
	_usersProfile.DeletedAt = field.NewField(tableName, "deleted_at")

	_usersProfile.fillFieldMap()

	return _usersProfile
}

type usersProfile struct {
	usersProfileDo usersProfileDo

	ALL       field.Asterisk
	ID        field.String
	UserID    field.String
	Email     field.String
	FirstName field.String
	LastName  field.String
	Headline  field.String
	Bio       field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (u usersProfile) Table(newTableName string) *usersProfile {
	u.usersProfileDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u usersProfile) As(alias string) *usersProfile {
	u.usersProfileDo.DO = *(u.usersProfileDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *usersProfile) updateTableName(table string) *usersProfile {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.UserID = field.NewString(table, "user_id")
	u.Email = field.NewString(table, "email")
	u.FirstName = field.NewString(table, "first_name")
	u.LastName = field.NewString(table, "last_name")
	u.Headline = field.NewString(table, "headline")
	u.Bio = field.NewString(table, "bio")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *usersProfile) WithContext(ctx context.Context) *usersProfileDo {
	return u.usersProfileDo.WithContext(ctx)
}

func (u usersProfile) TableName() string { return u.usersProfileDo.TableName() }

func (u usersProfile) Alias() string { return u.usersProfileDo.Alias() }

func (u usersProfile) Columns(cols ...field.Expr) gen.Columns {
	return u.usersProfileDo.Columns(cols...)
}

func (u *usersProfile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *usersProfile) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 10)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["email"] = u.Email
	u.fieldMap["first_name"] = u.FirstName
	u.fieldMap["last_name"] = u.LastName
	u.fieldMap["headline"] = u.Headline
	u.fieldMap["bio"] = u.Bio
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u usersProfile) clone(db *gorm.DB) usersProfile {
	u.usersProfileDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u usersProfile) replaceDB(db *gorm.DB) usersProfile {
	u.usersProfileDo.ReplaceDB(db)
	return u
}

type usersProfileDo struct{ gen.DO }

func (u usersProfileDo) Debug() *usersProfileDo {
	return u.withDO(u.DO.Debug())
}

func (u usersProfileDo) WithContext(ctx context.Context) *usersProfileDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u usersProfileDo) ReadDB() *usersProfileDo {
	return u.Clauses(dbresolver.Read)
}

func (u usersProfileDo) WriteDB() *usersProfileDo {
	return u.Clauses(dbresolver.Write)
}

func (u usersProfileDo) Session(config *gorm.Session) *usersProfileDo {
	return u.withDO(u.DO.Session(config))
}

func (u usersProfileDo) Clauses(conds ...clause.Expression) *usersProfileDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u usersProfileDo) Returning(value interface{}, columns ...string) *usersProfileDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u usersProfileDo) Not(conds ...gen.Condition) *usersProfileDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u usersProfileDo) Or(conds ...gen.Condition) *usersProfileDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u usersProfileDo) Select(conds ...field.Expr) *usersProfileDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u usersProfileDo) Where(conds ...gen.Condition) *usersProfileDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u usersProfileDo) Order(conds ...field.Expr) *usersProfileDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u usersProfileDo) Distinct(cols ...field.Expr) *usersProfileDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u usersProfileDo) Omit(cols ...field.Expr) *usersProfileDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u usersProfileDo) Join(table schema.Tabler, on ...field.Expr) *usersProfileDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u usersProfileDo) LeftJoin(table schema.Tabler, on ...field.Expr) *usersProfileDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u usersProfileDo) RightJoin(table schema.Tabler, on ...field.Expr) *usersProfileDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u usersProfileDo) Group(cols ...field.Expr) *usersProfileDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u usersProfileDo) Having(conds ...gen.Condition) *usersProfileDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u usersProfileDo) Limit(limit int) *usersProfileDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u usersProfileDo) Offset(offset int) *usersProfileDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u usersProfileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *usersProfileDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u usersProfileDo) Unscoped() *usersProfileDo {
	return u.withDO(u.DO.Unscoped())
}

func (u usersProfileDo) Create(values ...*model.UsersProfile) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u usersProfileDo) CreateInBatches(values []*model.UsersProfile, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u usersProfileDo) Save(values ...*model.UsersProfile) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u usersProfileDo) First() (*model.UsersProfile, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersProfile), nil
	}
}

func (u usersProfileDo) Take() (*model.UsersProfile, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersProfile), nil
	}
}

func (u usersProfileDo) Last() (*model.UsersProfile, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersProfile), nil
	}
}

func (u usersProfileDo) Find() ([]*model.UsersProfile, error) {
	result, err := u.DO.Find()
	return result.([]*model.UsersProfile), err
}

func (u usersProfileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UsersProfile, err error) {
	buf := make([]*model.UsersProfile, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u usersProfileDo) FindInBatches(result *[]*model.UsersProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u usersProfileDo) Attrs(attrs ...field.AssignExpr) *usersProfileDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u usersProfileDo) Assign(attrs ...field.AssignExpr) *usersProfileDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u usersProfileDo) Joins(fields ...field.RelationField) *usersProfileDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u usersProfileDo) Preload(fields ...field.RelationField) *usersProfileDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u usersProfileDo) FirstOrInit() (*model.UsersProfile, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersProfile), nil
	}
}

func (u usersProfileDo) FirstOrCreate() (*model.UsersProfile, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UsersProfile), nil
	}
}

func (u usersProfileDo) FindByPage(offset int, limit int) (result []*model.UsersProfile, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u usersProfileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u usersProfileDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u usersProfileDo) Delete(models ...*model.UsersProfile) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *usersProfileDo) withDO(do gen.Dao) *usersProfileDo {
	u.DO = *do.(*gen.DO)
	return u
}
