// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID             string         `gorm:"column:id;primaryKey" json:"id"`
	OrganizationID string         `gorm:"column:organization_id;not null" json:"organization_id"`
	Title          string         `gorm:"column:title;not null" json:"title"`
	CreatedAt      time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	IsOwner        bool           `gorm:"column:is_owner;not null" json:"is_owner"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
