// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrganization = "organizations"

// Organization mapped from table <organizations>
type Organization struct {
	ID        string         `gorm:"column:id;primaryKey" json:"id"`
	Category  string         `gorm:"column:category;not null" json:"category"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Active    bool           `gorm:"column:active;not null" json:"active"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
