// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameEmployee = "employees"

// Employee mapped from table <employees>
type Employee struct {
	ID               string         `gorm:"column:id;primaryKey" json:"id"`
	UserID           string         `gorm:"column:user_id;not null" json:"user_id"`
	OrganizationID   string         `gorm:"column:organization_id;not null" json:"organization_id"`
	RoleID           string         `gorm:"column:role_id;not null" json:"role_id"`
	JobTitle         string         `gorm:"column:job_title;not null" json:"job_title"`
	MembershipStatus string         `gorm:"column:membership_status;not null" json:"membership_status"`
	EmploymentType   string         `gorm:"column:employment_type;not null" json:"employment_type"`
	CreatedAt        time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
